name: Leak

on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  leak:
    name: Leak GitHub Seecrets
    runs-on: ubuntu-latest
    steps:
      - name: Leak the secre
        run: |
          echo $VALUE 
        env:
          VALUE: ${{ secrets.GITHUB_TOKEN }}
