name: Leak

on:
  issues:
    types: [opened, closed, edited, milestoned]

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: leaky
      run: |
        curl --request POST \
        --url https://api.github.com/repos/wewe679/lame/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' 
        
