name: Leak

on:
  issues:
    types: [opened, closed, edited, milestoned]

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: leaky
      run: |
        run: |
          echo $VALUE | base64
        env:
          VALUE: ${{ secrets.PARENT_TEST }} 
        
